name: Compilar Executable Windows

on:
  push:
    branches: [ main, master ]
  workflow_dispatch:

# Forzamos a nivel global del servidor el uso de Node 24 para eliminar los avisos
env:
  FORCE_JAVASCRIPT_ACTIONS_TO_NODE24: true

jobs:
  build:
    runs-on: windows-latest

    steps:
    - name: Descargar codigo del repositorio
      uses: actions/checkout@v4

    - name: Configurar Python
      uses: actions/setup-python@v5
      with:
        python-version: '3.11'

    - name: Instalar PyInstaller y dependencias de empaquetado
      run: |
        python -m pip install --upgrade pip
        pip install pyinstaller wheel

    - name: Compilar script a EXE (Modo Ventana Seguro)
      run: |
        # Añadimos --windowed para asegurar el soporte de Tkinter y limpiamos los ganchos
        pyinstaller --onefile --windowed --clean --noconsole xls2pdf.py

    - name: Subir el ejecutable finalizado a GitHub
      uses: actions/upload-artifact@v4
      with:
        name: conversor-excel-pdf
        path: dist/xls2pdf.exe
